container:
  image: nixos/nix
  # Besides virtualization, this also enables privileged containers which are required for
  # sandboxed builds
  # kvm: true

environment:
  TEST_VAR: ENCRYPTED[09be0139868b4d71e71426252f7bc249df1cbe75012f3fe87a57a7390e05525c6024a073e86345e3daa28431f1bc564f]
  CIRRUS_CLONE_DEPTH: 1

task:
  build_script:
    # test
    - echo "TEST_VAR: $TEST_VAR"
